### ISSUE TITLE
Transient errors when sending heartbeats can cause immediate lock loss

### ISSUE THREAD

**Issue by zdylag** [cirello-io/dynamolock#280]
It is possible for the `UpdateItem` call to error while actually succeeding on the server side. If this happens, the lock is immediately lost and no-one has it for one entire lease duration.

The order of operations that causes this is like so:
1. Create `newRvn1`
2. Call UpdateItem with `newRvn1`, and condition requiring `oldRvn`
3. DynamoDB updates item
4. <something goes wrong, possibly DynamoDB hangs on response, some network routing issues, a timeout, etc>
5. Client receives an error, so we *do not* update `oldRvn`
6. -- Next heartbeat --
7. Create `newRvn2`
8. Call UpdateItem with newRvn2, and condition requiring `oldRvn`
9. DynamoDB correctly returns a condition failed error, since the rvn was actually `newRvn1`

---

For context: we were able to see this in our production environment in two different ways:

- Calling `SendHeartbeatWithContext` with a timeout on the context. This can cause a race between the client giving up on the request and the request returning success.
- DynamoDB returning an internal service error status code but actually succeeding. 

---

We wanted to file an issue first to gather feedback, but we had an initial idea to solve this:
- Add a new `RvnLookback` option to the client, defaulting to 0.
- Add a circular buffer in the `Lock` struct for "attemptedRvns".
- When constructing the update condition, instead of checking Rvn equality, check if Rvn is in [current, circularbuffer...].
- When heartbeating, always add the newly generated Rvn to the buffer, regardless of the success of the update.

We are happy to take on this work and open a pull request if this seems reasonable.

**Comment by ucirello** [comment]
hi @zdylag -- I must say I am a bit confused with your message. I should probably update the README.md to indicate that dynamolock is an optimistic concurrency control. Pessimistic locking fits the bill of the intended behavior you are describing.

If DynamoDB misbehaves or if there is a network partition, the right thing to do is to assume that you lost the lock - and not try to resurrect it.

Couple of suggestions: 

1. You can not use context with your heartbeats - this will deal with one of your situations. The idea of heartbeats using context is so that it can interrupt the call, essentially ignoring its outcome.
2. You can use an application level RVN instead, and then rely on that. You can user the `Get` call instead, and then keep track of your own application level RVN, and then deciding if you are happy or not with the current lock. And if you happen to not be happy with the lock you can decide to wait, or to grab the lock again with another key based off of the RVN.
3. Heartbeats are meant to allow for locks to be hold for an arbitrarily amount of time. If you know before hand the duration of your locks, you can disable automatic heartbeats, and then heartbeat once before the lock is released. 

I hope these suggestions help. But in any case, I strongly advise you to switch to a pessimistic locking mechanism instead. The good news is that if you want to go down the pessimistic locking route, you don't need dynamolock at all. Just use a DynamoDB transaction, like:

```
input := &dynamodb.TransactWriteItemsInput{
	TransactItems: []*dynamodb.TransactWriteItem{{
		Update: &dynamodb.Update{
			// the rest of the update configuration goes here.

			// sets the lock...
			UpdateExpression: aws.String("set #locked = :lockValue"), // sets the lock
			ExpressionAttributeNames: map[string]*string{ "#locked": aws.String("locked"), },
			ExpressionAttributeValues: map[string]*dynamodb.AttributeValue{ ":lockValue": { S: aws.String("true"), }, },

			// ...but only if it is not locked.
			ConditionExpression: aws.String("attribute_not_exists(locked) or #locked = :falseValue"),
			ExpressionAttributeValues: map[string]*dynamodb.AttributeValue{ ":falseValue": { S: aws.String("false"), }, },
		},
	}},
}
_, err := client.svc.TransactWriteItems(input)
```

And to check if the entry is locked, you can use: 
```
client.svc.GetItem(&dynamodb.GetItemInput{
	// Add the table name and key

	// ... and make sure you're using consistent reads.
	ConsistentRead: aws.Bool(true),
})
```

Good luck!

**Comment by zdylag** [comment]
@ucirello I think I just did a poor job explaining things, hopefully I can do better this time.

My issue is not with the type of locking we are doing or with the behavior if things are truly lost. I am bringing this up as an optimization in lock utilization by making the library more resilient to transient failures. 

In particular, at scale it is possible to enter a state where one client *does* have the lock but does not realize it. It is actually completely safe to recover from here, as we can ensure no-one else has the lock, we just need some extra code to do so.

We know it is safe to continue in this case because we know the Rvn(s) which we have generated, and we can verify that the lock belongs to us (and has not been lost to another client).

Another way to approach fixing this class of error might be to issue a strongly consistent read against the lock after any "failed" write operation. That would let us check if the failure happened before or after state was updated in the database. By doing so we could safely continue knowing we hold the lock and recover from this situation.

Does that make sense?

**Comment by ucirello** [comment]
@zdylag Thanks for the thoughtful reply. I am going to try an characterize the situation you put forward in code before debating this further. If you happen to have a snippet of code that characterizes the situation, then please add them to `gist` and share with me. Thank you.

**Comment by ucirello** [comment]
@zdylag - I managed to artificially characterize the situation you describe in code. Please test with the current HEAD (e6159c324401250c0973d2ab7b8ed35acdfdeca5).

This implementation will insist running the heartbeat until it succeeds. That helped keeping the logic simpler, instead of carrying along a heartbeat's RVN into the next one.

**Comment by zdylag** [comment]
Very fast work wow! Thanks for doing this!

I spent some time writing some tests to try to reproduce the situations we have seen and I _believe_ the changes made largely fix things for transient DDB side errors, but not for timeouts (for v2). I pushed the tests up to a branch so you can see them https://github.com/zdylag/dynamolock/commit/eec4b4031fcbe8e90492ba4355d2e843140134d6

For our use case: we have seen great benefits from enforcing timeouts in general. What do you think about revisiting this change so that it cooperates with timeouts?

One approach might be to have a "WithPerRequestTimeout" option on the client. Another might be to split this callsite up so clients somehow do the retries? Finally we could go back to the "carry the RVN forward" approach.

**Comment by ucirello** [comment]
Thanks for getting back, I will take a look at your tests cases.

I consider the RVN carry over a solution of last resort that could mask deeper problems. 

> I spent some time writing some tests to try to reproduce the situations we have seen and I believe the changes made largely fix things for transient DDB side errors, but not for timeouts (for v2).

Why would WithPerRequestTimeout help the situation?

**Comment by ucirello** [comment]
@zdylag -- I read the code you shared, thank you. 

You should use a pessimistic lock. A pessimistic locking system would solve both of these problems you put forward (in a proper pessimistic locking implementation, every lock is mutually acknowledged by the client and the server before being made permanent; in this scenario, for instance, you would use something like Chubby).

dynamolock is an _optimistic_ locking system - that by definition, gives up on any other situation than success.

When you cancel a call, the cancelation may happen at any time, anywhere - all bets are off. And any consistent state is accidental and cannot be relied on.

I will keep `HeartbeatRetries` for v2, and re-evaluate its value for v3.

But to not leave you hanging, you can set timeouts at the DynamoDB client level:
```
dynamoDBClient := dynamodb.New(sess, aws.NewConfig().WithHTTPClient(&http.Client{
	Timeout: 10*time.Second * 10,
}))
```

Ensure that the HTTP Client timeout is longer than the context deadline. The locking call will give up before the HTTP Client times out. And if you are generous with the HTTP Client timeout, you can have extensive retries.

**Comment by ucirello** [comment]
I added an unsafe mode that should address the client-side network flakiness: https://github.com/cirello-io/dynamolock/commit/3f5f7fbca66b77a001b357c12822ceaaff0be8e9

**Comment by zdylag** [comment]
Thanks for the fixes and the pointers! I think we will sit and let the changes bake for a long while before deciding what to do next, but we really appreciate the quick responses!
