### ISSUE TITLE
please provide a channel-based expiration API

### ISSUE THREAD

**Issue by costela** [cirello-io/dynamolock#42]
Hi,

I believe it would be nice to have a `chan` based mechanism for being notified of lock expiration. This would make some use-cases slightly more usable by avoiding polling on `lock.IsExpired()`.

I'll try to cook up a small PR to get the ball rolling.

**Comment by ucirello** [comment]
This seems a legitimate problem. I wonder whether we should replicate here the `Do` interface from pglock - https://godoc.org/cirello.io/pglock#Client.Do

I suggest you propose this design change here first before crafting a PR. In its current state #43 is wrong.

**Comment by ucirello** [comment]
Probably a good angle to start attacking this need is by understanding what are the events the generate a lock release (either by intention or accidental loss) and probably plug into that even a channel-based API.

**Comment by costela** [comment]
Personally I'd go for a first sound approach first (or at least as sound as a non-quorum-based distributed lock can be), and plug separate event sources later. The current attempt at #43 does this: it encapsulates the polling away from the user and accomodates for heartbeats "refreshing" the lock. AFAICT it is as sound as `IsExpired()`.

As far as I can see in the code (I might of course be missing something), there are no other sources of expiration. Intentional release is a different story: I personally would not expect the API to protect me from myself: if I'm actively releasing, it's my responsibility to stop waiting for expiration.

What other sort of events did you have in mind?

**Comment by costela** [comment]
OTOH, if you think the `Lock.Expiration()` channel should also report releases, that would also be doable, of course.

**Comment by ucirello** [comment]
I think `IsExpired()` and `OnExpiration()` should both have the same meaning - they would be different delivery modes but have the same meaning.

**Comment by ucirello** [comment]
Another important concern is that `OnExpiration` should neither leak goroutines nor block after notification. Meaning probably its signature would be `OnExpiration(context.Context)`. If this is suppose to block and send a message in a channel, we should probably leave the channel out of its API.

Thusly, not this:
```
Expiration() chan struct{}
```

but
```
WaitExpiration(ctx context.Context)
```
(where WaitExpiration is a blocking call - no need to expose channels)

What do you say?

**Comment by costela** [comment]
> I think IsExpired() and OnExpiration() should both have the same meaning

Fair point.

> Another important concern is that OnExpiration should neither leak goroutines nor block after notification

In its current implementation, it doesn't leak goroutines as long as the lock eventually expires. The blocking also shouldn't be a problem, with the same assumption. AFAICT it's impossible to provide an "infinite" `leaseDuration`, in which case this assumption would be safe.
However, a couple of extra tests for those cases wouldn't hurt. I'll give it a shot tomorrow.

> Meaning probably its signature would be OnExpiration(context.Context)

IMHO a `context` is overkill in this case. The "price" of a single goroutine per lock, sleeping for `leaseDuration` too long, in the worst case, seems very small in comparison.
In the end it's your call, of course.

> If this is suppose to block and send a message in a channel, we should probably leave the channel out of its API.

I respectfully disagree. Channels offer us the very powerful option of `select`ing on them. And it's very easy to convert a channel-returning function into a blocking one:
```go
<-lock.OnExpiration()
``` 
The other way around is not as easy or elegant.

**Comment by ucirello** [comment]
> In its current implementation, it doesn't leak goroutines as long as the lock eventually expires. The blocking also shouldn't be a problem, with the same assumption. AFAICT it's impossible to provide an "infinite" leaseDuration, in which case this assumption would be safe.

> IMHO a context is overkill in this case. The "price" of a single goroutine per lock, sleeping for leaseDuration too long, in the worst case, seems very small in comparison.
In the end it's your call, of course.

Goroutines are cheap, but they are not free. Also, how would you handle the situation in which the caller doesn't want to wait for the lock anymore? In the case of a coarse-grained lock, let's say of 24h, the worst-case scenario is a goroutine hanging around for 24h? If I understand what you are proposing, it does not seem to be the correct behavior.

> I respectfully disagree. Channels offer us the very powerful option of selecting on them. And it's very easy to convert a channel-returning function into a blocking one

I understand where you are coming from. It is also quite easy to convert a blocking call into a channel returning function. Here's an elegant and small function that anyone can use, that doesn't complicate the library implementation.

```
func observeLock(lock *dynamolock.Lock) <-chan struct{}
        done := make(chan struct{})
        go func(){
                lock.WaitExpiration(...)
                close(done)
        }()
        return done
)
```

I guess the main difference is that in Go unless told otherwise, all functions are blocking - that's why there is the `go` keyword. This library should make the code using it to be felt as Go as the standard library would be. I benchmark Go libraries API design to what the Go's standard library does. There you almost don't see functions returning channels for single notifications, they just block. `net.Listener.Accept`, `os.File.Read` and many more from the standard library are examples of blocking calls and help us understand what defines Go code to feel Go code. 

Returning a channel is a tricky thing. The message may not be consumed (if there is no consumer - a mistake easy to make if someone just invokes `lock.OnExpiration()` without the receiving arrow; if implemented with a buffered channel, then the OnExpiration may assume the message was consumed, when in fact, it wasn't ) or the message may not delivered (if to avoid blocking in the channel, a `select` block with `default` is used).

Making this a blocking call allows us to say: "this hangs until it is done". At that point is up to the user to add more abstractions to expose this interface with a channel and shifts the responsibility to the user of the library on how to handle that.

In any case, I think we should approach this divergence between returning a channel or not with some real-world source code corpus analysis. Can you please provide a handful of real-world source code snippets and show how these two implementations weight against each other? The more concrete the cases are, the better.

**Comment by ucirello** [comment]
One a side note, I wonder how this call would interact when the client is started with heartbeats disabled.

**Comment by ucirello** [comment]
> One a side note, I wonder how this call would interact when the client is started with heartbeats disabled.

I finished investigating this, and it won't matter.

**Comment by costela** [comment]
> Goroutines are cheap, but they are not free.

Yes, that's why I mentioned _price_. It's a clear trade-off.
But if you prefer a slight increase in API complexity to cover the long-lease case, that's also fine.

> I benchmark Go libraries API design to what the Go's standard library does.

The standard library doesn't attempt to deal with distributed (in the multi-agent sense) cases, so it has a different set of limitations to work with. Not to mention the fact that it must strive to be a least common denominator of sorts. So it's not clear what your point here is.

> net.Listener.Accept, os.File.Read and many more from the standard library are examples of blocking calls and help us understand what defines Go code to feel Go code.

Are they?
They are blocking calls because it would make considerably less sense to assume asynchronicity when you are expecting a workable return value (the `Conn` in the first case; the file data in the second).
A much more valid comparison would be with `Context.Done()` or with `CloseNotifier.CloseNotify()`. These are cases where asynchronicity is intrinsic to the problem at hand (just like the distributed lock case).
The standard library does not attempt to solve problems at this level, so using it as a yardstick seems somewhat arbitrary.

> Can you please provide a handful of real-world source code snippets and show how these two implementations weight against each other?

Probably not. The amount of work that would entail unfortunately overshadows the subjective improvement to the API we would get.

**Comment by ucirello** [comment]
> Are they?
They are blocking calls because it would make considerably less sense to assume asynchronicity when you are expecting a workable return value (the Conn in the first case; the file data in the second).
A much more valid comparison would be with Context.Done() or with CloseNotifier.CloseNotify(). These are cases where asynchronicity is intrinsic to the problem at hand (just like the distributed lock case).
The standard library does not attempt to solve problems at this level, so using it as a yardstick seems somewhat arbitrary.

Fair point.

> Probably not. The amount of work that would entail unfortunately overshadows the subjective improvement to the API we would get.

Thanks for the suggestion all the same.
