### ISSUE TITLE
Composite key support and checking lock before aquiring

### ISSUE THREAD

**Issue by wongkristen** [cirello-io/dynamolock#76]
Hi @ucirello --

I just have a couple of questions about some features that are currently available in the Java version of the DynamoDB lock client developed by AWS Labs, but not yet available in this in this Go version:

1. Do you plan to add support for lock tables with composite keys? Currently the lock client only supports tables with partition key only and has no option for providing the sort key:

**Line 583, client.go:**
```Go
func (c *Client) readFromDynamoDB(key string) (*dynamodb.GetItemOutput, error) {
	dynamoDBKey := map[string]*dynamodb.AttributeValue{
		c.partitionKeyName: {S: aws.String(key)},
	}
	return c.dynamoDB.GetItem(&dynamodb.GetItemInput{
		ConsistentRead: aws.Bool(true),
		TableName:      aws.String(c.tableName),
		Key:            dynamoDBKey,
	})
}
```

For tables that have both partition and sort key, this causes an error:
```
ValidationException: The provided key element does not match the schema
```

2. Is there a way to check if a lock is already being held by someone else after calling `client.Get(key)`? Something like calling `lock.IsReleased()` before attempting to call `client.AcquireLock(..)`? I'm not so sure that the `lock.IsExpired()` method fully covers this.

Thank you for your continued help and support of this package :)

**Comment by ucirello** [comment]
hi @wongkristen 

I have limited availability to work on this package and keep it on par with the Java one. This means it has fewer features. Now to your questions:

> 1. Do you plan to add support for lock tables with composite keys?

I don't have plans as of now, but PRs are very welcome. I didn't do it because I didn't need it, but I can see it being useful for the whole user base.

> 2. Is there a way to check if a lock is already being held by someone else after calling client.Get(key)? Something like calling lock.IsReleased() before attempting to call client.AcquireLock(..)? I'm not so sure that the lock.IsExpired() method fully covers this.

Could you perhaps elaborate on exactly what you want to accomplish? This question has a bit of XY problem feeling and I am not sure the right way to answer it. You could call `Get()` every time you need a fresh view of the state of the lock or query the table. Again - perhaps if you elaborate more on what you are trying to achieve I am going to be able to give you a more meaningful answer.

**Comment by ucirello** [comment]
ping @wongkristen

**Comment by wongkristen** [comment]
Hey @ucirello, thanks for the quick response!

1. I will keep this in mind, maybe send a PR your way in the future :)
2. I believe I found a solution for my issue with this.

I really appreciate your help and support, closing out this issue.
