### ISSUE TITLE
Support serialization of locks or allow acquire to succeed if we already own the lock.

### ISSUE THREAD

**Issue by taylor-sutton** [cirello-io/dynamolock#83]
In my use case, a lock is held during the course of a workflow which spans multiple services. I have not found a way to do this using `dynamolock` as:
* `Lock` can't be serialized in any meaningful way since it doesn't export any fields.
* I could imagine trying to use `AcquireLock` with the same owner to essentially heartbeat the lock and have the second service create a `Lock`. But that doesn't work. 

Is this a use case that `dynamolock` could/should, conceptually, support? Addressing either the first point by adding a `Lock.Serialize()` and `dynamolock.FromSerialization()` in some form, or having the second thing work? I would be willing to work on a PR, but would prefer to get some guidance on whether it would be worth doing first.

**Comment by ucirello** [comment]
thanks for the question @taylor-sutton 

I must say that both proposition feels a bit XYProblem-kind solutions for me (http://xyproblem.info/).

It seems that you have a sequential pipeline and you'd want to rely on a single lock to coordinate the hand-over between the steps of this pipeline. If I understood you correctly, none of those propositions would work.

Serializing the current state of the lock only works if the hand-over doesn't happen on the verge of the heartbeat. If some other entity is competing for the lock, and then you serialize it and hand it over to the next step, the first entity is going to grab the lock and you are going to hand a stale-but-looking-good lock.

Also, using the client owner as the proxy of lock ownership is a brittle proposition, because it relies on the need of a human not making a mistake of deploying to clients with the same owner. I have seen it more often fail than succeed. That's why this current design doesn't rely on the owners for decision making -- owners are useful for inspection, to understand what entities of your systems are doing.

From what I gather, what you need is to use the Lock as mutex and not as wait-queue.My suggestion then is: store the current step of the processing in a number in DynamoDB and use this library to coordinate its updates and reads. Each step, before starting, grabs the lock and reads the number -- if this number corresponds to the step that needs to be executed, you update the number, release the lock and proceed. If the numbers don't match, you release the lock and try again.

Would it work for you?

**Comment by ucirello** [comment]
Hey @taylor-sutton - I am going to close this issue. Please reopen it if you need more support. Thanks
